### ISSUE TITLE
Bot Crash

### ISSUE THREAD

**Issue by rovertdude** [TotalCore/MusicBot#4]
Savnith - Today at 7:15 PM
;play savnith abus
Music PugBOT - Today at 7:15 PM
Traceback (most recent call last):
  File "C:\Users\tsann\MusicBot\musicbot\bot.py", line 1912, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\tsann\MusicBot\musicbot\bot.py", line 847, in cmd_play
    await self.send_typing(channel)
  File "C:\Users\tsann\MusicBot\musicbot\bot.py", line 522, in send_typing
    return await super().send_typing(destination)
  File "C:\Users\tsann\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 905, in send_typing
    yield from utils._verify_successful_response(response)
  File "C:\Users\tsann\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\utils.py", line 238, in _verify_successful_response
    raise HTTPException(response, message, text)
discord.errors.HTTPException: Bad Gateway (status code: 502)
Bot crashed.

**Comment by rovertdude** [comment]
Anything with ;play savnith does this

**Comment by adroition** [comment]
Invalid - bot did not crash due to this
